apiVersion: apps/v1
kind: Deployment
metadata:
  name: testsite 
  labels:
{{- include "default.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testsite 
  template:
    metadata:
      labels:
        app: testsite 
    spec:
      containers:
      - name: testsite
        image: nginx 
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: nginx-configmap
      volumes:
        - name: nginx-configmap
          configMap:
            name: testsite-configmap

