apiVersion: v1
kind: Service
metadata:
  name: testsite-service 
  labels:
{{- include "default.labels" . | indent 4 }}
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: testsite
