apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: testsite-ingress
  labels:
{{- include "default.labels" . | indent 4 }}
spec:
  rules:
  - host: "{{ .Values.ingress.host }}" 
    http:
      paths:
      - path: /
        backend:
          serviceName: testsite-service 
          servicePort: 80
  tls:
  - hosts:
    - "{{ .Values.ingress.host }}"
    secretName: ingress-certificate

