apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ingress-certificate
  labels:
{{- include "default.labels" . | indent 4 }}
spec:
  secretName: ingress-certificate
  issuerRef:
    kind: ClusterIssuer
    name:  letsencrypt-production-issuer
  dnsNames:
  - "*.{{ .Values.domain }}"
  - "{{ .Values.domain }}"
