# Placeholder secret is created first and annotated with kubed/sync so that it will be synced to
# other namespaces. 
# Empty values are filled in by the cert-manager when the certificate is provisioned..
apiVersion: v1
data:
  tls.crt: ""
  tls.key: ""
kind: Secret
metadata:
  annotations:
    kubed.appscode.com/sync: ""
  name: ingress-certificate
  namespace: cert-manager
type: kubernetes.io/tls
